# Generated by Django 4.1.7 on 2023-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doctorId', models.IntegerField(null=True, verbose_name='主治医生ID')),
                ('patientId', models.IntegerField(null=True, verbose_name='患者ID')),
                ('patientName', models.CharField(max_length=255, null=True, verbose_name='患者姓名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reserve_time', models.DateTimeField(null=True, verbose_name='预约时间')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
                ('healthStatus', models.CharField(max_length=100, null=True, verbose_name='健康状态')),
                ('imageId', models.IntegerField(null=True, verbose_name='图像上传记录ID')),
                ('patientRemark', models.TextField(null=True, verbose_name='患者备注')),
                ('reportWordName', models.CharField(max_length=255, null=True, verbose_name='检测报告单名字')),
                ('medicalWordName', models.CharField(max_length=255, null=True, verbose_name='病历单名字')),
                ('isFinished', models.IntegerField(default=0, verbose_name='是否生成了病例文档')),
            ],
            options={
                'verbose_name': '患者求诊记录',
                'verbose_name_plural': '患者求诊记录',
                'db_table': 'patient_record',
            },
        ),
    ]
