# Generated by Django 4.1.7 on 2023-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='用户电话')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('card', models.CharField(max_length=30, null=True, verbose_name='身份证')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='居住地址')),
                ('gender', models.IntegerField(null=True, verbose_name='性别')),
            ],
            options={
                'verbose_name': '医生信息',
                'verbose_name_plural': '医生信息',
                'db_table': 'doctor_profile',
            },
        ),
    ]
