# Generated by Django 4.1.7 on 2023-04-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='nation',
            field=models.CharField(max_length=200, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(max_length=10, null=True, verbose_name='性别'),
        ),
    ]
